### ISSUE TITLE
With active plugin right click in file manager doen't work

### ISSUE THREAD

**Issue by ATaimasov** [HoBeom/obsidian-mouse-navigation#2]
It's a good idea to add gestures into obsidian, thank you for this! 

But I meet a bit issue with using this plugin.  
The problem is in unworking contex menu in file manager. Gestures still work in file manager window and it's likely interrupt opening context menu for each file.

**Comment by Hobeom** [comment]
Thank you for bringing up this issue! 
I was able to reproduce the problem on my end, and I believe it might be related to the theme settings.

**Comment by Hobeom** [comment]
I’ve recently implemented updates to address this issue, ensuring that the plugin no longer interferes with the right-click context menu in the File Manager. Could you please confirm if the issue is resolved in the latest version of the plugin? Your feedback would be greatly appreciated.

Thank you once again for your patience and support! 😊

**Comment by ATaimasov** [comment]
Yep, this problem is gone. 
The plugin becomes more comfortable now. It's really good!

Thank you!
